[general]
import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[font]
size = 11

[font.normal]
family = 'monospace'
style = 'Regular'

[font.bold]
family = 'monospace'
style = 'Regular'

[env]
TERM="xterm-256color"

[colors]
transparent_background_colors = true
